### ISSUE TITLE
`prefixes` is not defined

### ISSUE THREAD

**Issue by llaski** [mathiasbynens/jquery-visibility#21]
When the variables were reorganized `prefixes` was renamed to `vendorPrefixes` but where it was used remained as `prefixes` so just needs to be updated.

https://github.com/mathiasbynens/jquery-visibility/commit/6203468c8ce98254ccce0ff7910382f74b6ae921

**Comment by janpaepke** [comment]
well that's embarrassing. =)
I originally wanted to rewrite the loop too, but decided not to.
When reverting, I must have gone one step too far. :(

thx 4 reporting.
