### ISSUE TITLE
Consider changing this=>root to window=>root

### ISSUE THREAD

**Issue by pgilad** [mathiasbynens/jquery-visibility#22]
This code won't work on a node.js global, and the main issue is that using Webpack on this plugin requires shimming it with:
```js
module: { loaders: {
        test: /node_modules\/jquery-visibility\/jquery-visibility\.js$/,
        loaders: ['imports?this=>window']
}}
```

Since Webpack (for some reason) evaluates the context to that of the module.

I would suggest perhaps changing:
`}(this, function(window, $, undefined) {`

to:
`}(window, function(window, $, undefined) {`

In order to provide full compatibility.

**Comment by pgilad** [comment]
I opened a ticket on Webpack as well, asking for an explanation for this behavior:
https://github.com/webpack/webpack/issues/1141

**Comment by janpaepke** [comment]
Pls update us what they have to say about it and then we'll decide how to proceed. :)

**Comment by pgilad** [comment]
Hey @janpaepke Can this change be made?

**Comment by janpaepke** [comment]
yes it can, haven't had the time to work on it though. feel free to send pr
