### ISSUE TITLE
Syntax error when minify'ing w/ Uglify...

### ISSUE THREAD

**Issue by busticated** [mathiasbynens/jquery-visibility#4]
Hey there -

Thanks a bunch for this plugin - it's been super-helpful. I really appreciate how focused it is :-)

I ran into an issue which I detail a bit over here:

https://github.com/mishoo/UglifyJS2/issues/60

Figured I'd cross-link here if only as an FYI to others. 

To fix, I just re-wrote it using a boring old if()

    var prefix,
        property,
        eventName = 'focus blur',
        prefixes = ['', 'moz', 'ms', 'o', 'webkit'],
        $support = $.support,
        $event = $.event;

     // In Opera, `'onfocusin' in document == true`, hence the extra `hasFocus` check to detect IE-like behavior
    if ('onfocusin' in document && 'hasFocus' in document) {
        eventName = 'focusin focusout';
    }

Hope it helps!
-matt

**Comment by janpaepke** [comment]
Doesn't seem to be an issue with the current version anymore.
thx 4 reporting.
