### ISSUE TITLE
originalEvent is undefined

### ISSUE THREAD

**Issue by QuentinFchx** [mathiasbynens/jquery-visibility#8]
I had the issue when triggering a focus event on an input

We should test if originalEvent exist before getting its property "toElement".

http://bugs.jquery.com/ticket/8055

>The  Event-object documentation says:
>Certain native events may have special properties that can be accessed as properties of the event.originalEvent object.
>
>The  trigger() documentation (.focus() is short for .trigger("focus")) says:
>Although .trigger() simulates an event activation, complete with a synthesized event object, it does not perfectly replicate a naturally-occurring event.
>
>As triggering focus with .focus() isn't a native event, the originalEvent property can't available.

**Comment by janpaepke** [comment]
was fixed.
